set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN J1 [get_ports VCC]
set_property IOSTANDARD LVCMOS33 [get_ports VCC]
set_property PACKAGE_PIN L2 [get_ports music]
set_property IOSTANDARD LVCMOS33 [get_ports music]
set_property PACKAGE_PIN J2 [get_ports GND]
set_property IOSTANDARD LVCMOS33 [get_ports GND]

set_property IOSTANDARD LVCMOS33 [get_ports MusicCol]
set_property PACKAGE_PIN V17 [get_ports MusicCol]

set_property PACKAGE_PIN A15 [get_ports H1]
set_property PACKAGE_PIN A17 [get_ports H2]
set_property PACKAGE_PIN C15 [get_ports H3]
set_property PACKAGE_PIN C16 [get_ports H4]
set_property PACKAGE_PIN L17 [get_ports V1]
set_property PACKAGE_PIN M19 [get_ports V2]
set_property PACKAGE_PIN P17 [get_ports V3]
set_property PACKAGE_PIN R18 [get_ports V4]
set_property IOSTANDARD LVCMOS33 [get_ports H1]
set_property IOSTANDARD LVCMOS33 [get_ports H2]
set_property IOSTANDARD LVCMOS33 [get_ports H3]
set_property IOSTANDARD LVCMOS33 [get_ports H4]
set_property IOSTANDARD LVCMOS33 [get_ports V1]
set_property IOSTANDARD LVCMOS33 [get_ports V2]
set_property IOSTANDARD LVCMOS33 [get_ports V3]
set_property IOSTANDARD LVCMOS33 [get_ports V4]
set_property PULLUP true [get_ports V1]
set_property PULLUP true [get_ports V2]
set_property PULLUP true [get_ports V3]
set_property PULLUP true [get_ports V4]

set_property IOSTANDARD LVCMOS33 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[0]}]
set_property PACKAGE_PIN W7 [get_ports {data_out[7]}]
set_property PACKAGE_PIN W6 [get_ports {data_out[6]}]
set_property PACKAGE_PIN U8 [get_ports {data_out[5]}]
set_property PACKAGE_PIN V8 [get_ports {data_out[4]}]
set_property PACKAGE_PIN U5 [get_ports {data_out[3]}]
set_property PACKAGE_PIN V5 [get_ports {data_out[2]}]
set_property PACKAGE_PIN U7 [get_ports {data_out[1]}]
set_property PACKAGE_PIN V7 [get_ports {data_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN U2 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN U4 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN V4 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN W4 [get_ports {seg_sel[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports out_sign]
set_property PACKAGE_PIN L1 [get_ports out_sign]
set_property IOSTANDARD LVCMOS33 [get_ports carry_flag]
set_property IOSTANDARD LVCMOS33 [get_ports out_less]
set_property IOSTANDARD LVCMOS33 [get_ports out_zero]
set_property PACKAGE_PIN P1 [get_ports out_less]
set_property PACKAGE_PIN N3 [get_ports out_zero]
set_property PACKAGE_PIN P3 [get_ports carry_flag]



#set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
#set_property PACKAGE_PIN E19 [get_ports {state[1]}]
#set_property PACKAGE_PIN U16 [get_ports {state[0]}]
