# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/VivadoProject/MusicCalc/MusicCalc.cache/wt [current_project]
set_property parent.project_path F:/VivadoProject/MusicCalc/MusicCalc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/VivadoProject/MusicCalc/MusicCalc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/PreKey.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/NumSelect.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/NumInput.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/Key_Driver.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/FlagPulse.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/seg.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/NoteTrans.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/MusicState.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/MusicSheet.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/MusicGen.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/MusicCnt.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/key_scan.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/FreqDiv.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/Hex2Dec.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/CoreCircuit.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/ALU.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/Music.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/Calc.v
  F:/VivadoProject/MusicCalc/MusicCalc.srcs/sources_1/new/MusicCalc.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/VivadoProject/MusicCalc/MusicCalc.srcs/constrs_1/new/Key_test_PIN.xdc
set_property used_in_implementation false [get_files F:/VivadoProject/MusicCalc/MusicCalc.srcs/constrs_1/new/Key_test_PIN.xdc]


synth_design -top MusicCalc -part xc7a35tcpg236-1


write_checkpoint -force -noxdef MusicCalc.dcp

catch { report_utilization -file MusicCalc_utilization_synth.rpt -pb MusicCalc_utilization_synth.pb }
